import type { CompletionRequest, CompletionResult, LLMProvider } from "./types.js";

const QA_REVIEW_MARKER = "VERDICT: PASS or REVISE";
const QA_360_MARKER = "OVERALL ENGAGEMENT GRADE";
const ENGAGEMENT_PLAN_MARKER = "ENGAGEMENT_TYPE:";

const QA_PASS_RESPONSE = `VERDICT: PASS
SCORES:
- strategic_fit: 9
- methodology: 8
- analytical_depth: 8
- commercial_actionability: 9
- client_readiness: 8
- risk_compliance: 9
OVERALL: 8.5
CRITIQUE:
[MOCK] No real review performed — this is a canned PASS from the mock provider so pipeline wiring can be tested without network calls.`;

const QA_360_RESPONSE = `[MOCK 360 ANALYSIS] Client Value: n/a (mock). Methodological Soundness: n/a (mock). Commercial Risk: n/a (mock).
Operational Feasibility: n/a (mock). Competitive Differentiation: n/a (mock). Actionability: n/a (mock).

OVERALL ENGAGEMENT GRADE: A
SHIP DECISION: SHIP IT`;

const ENGAGEMENT_PLAN_RESPONSE = `[MOCK] Methodology: mixed-methods (canned mock decision).

ENGAGEMENT_TYPE: full_mixed_methods
NEEDS_QUALITATIVE: yes
NEEDS_QUANTITATIVE: yes
NEEDS_FIELDWORK: yes
NEEDS_DATA_ANALYSIS: yes
PLAN_RATIONALE: [MOCK] deterministic full-scope plan so pipeline wiring exercises every role in tests.`;

/**
 * Deterministic offline provider used by tests and `--mode mock` dry-runs so the
 * pipeline wiring can be verified without spending real API credits or requiring
 * auth. Recognizes the QA reviewer's and Research Director's structured-output
 * requests (by their required-format markers) and answers them in the expected
 * tagged format, so the QA loop and dynamic-scoping parser have something real
 * to parse even offline.
 */
export class MockProvider implements LLMProvider {
  readonly name = "mock";

  isAvailable(): boolean {
    return true;
  }

  async complete(req: CompletionRequest): Promise<CompletionResult> {
    let text: string;
    if (req.system.includes(QA_REVIEW_MARKER)) {
      text = QA_PASS_RESPONSE;
    } else if (req.system.includes(QA_360_MARKER)) {
      text = QA_360_RESPONSE;
    } else if (req.system.includes(ENGAGEMENT_PLAN_MARKER)) {
      text = ENGAGEMENT_PLAN_RESPONSE;
    } else {
      const roleLine = req.system.split("\n")[0]?.slice(0, 80) ?? "agent";
      text = [
        `[MOCK OUTPUT from ${roleLine}]`,
        "",
        `Responding to: ${req.prompt.slice(0, 160)}${req.prompt.length > 160 ? "…" : ""}`,
        "",
        "This is placeholder text generated by the mock provider (no LLM was called).",
      ].join("\n");
    }

    return { text, providerName: this.name, route: this.name };
  }
}
