import type { CompletionRequest, CompletionResult, LLMProvider } from "./types.js";

/**
 * Deterministic offline provider used by tests and `--mode mock` dry-runs so the
 * pipeline wiring can be verified without spending real API credits or requiring auth.
 */
export class MockProvider implements LLMProvider {
  readonly name = "mock";

  isAvailable(): boolean {
    return true;
  }

  async complete(req: CompletionRequest): Promise<CompletionResult> {
    const roleLine = req.system.split("\n")[0]?.slice(0, 80) ?? "agent";
    const text = [
      `[MOCK OUTPUT from ${roleLine}]`,
      "",
      `Responding to: ${req.prompt.slice(0, 160)}${req.prompt.length > 160 ? "…" : ""}`,
      "",
      "This is placeholder text generated by the mock provider (no LLM was called).",
    ].join("\n");

    return { text, providerName: this.name, route: this.name };
  }
}
